plugins:
  - jekyll-seo-tag
name: sajjad asadi personal homepage
description: This is sajjad asadi personal homepage.
author: sajjad asadi
author_email: lvlr.xaus@gmail.com
url: https://lvlrsajjad.github.io/
social:
  name: sajjad asadi
  links:
    - https://www.linkedin.com/in/sajjad-asadi
    - https://github.com/lvlrSajjad